id: 8a208932-bae3-485b-ba52-0da91625b992
type: web-application
interactions:
- targetId: e177a22a-877c-4c64-a91e-65b1e5bc3771
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    53826328-919f-485b-a684-f667236c8306:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: 89a40220-1932-4ae3-9a7a-3d6c86a087b7
  type: application
- id: 60d6bffd-63af-49b5-b5c2-dcfa65cc45fe
  type: domain
- id: b254c825-0fef-4135-bf76-fd0e183a1b79
  type: scenario
